### ISSUE TITLE
Remove center datetime

### ISSUE THREAD

**Issue by gadomski** [stactools-packages/esa-cci-lc#6]
In the case of (e.g.) yearly datasets, we have been just setting `start_datetime` and `end_datetime`, e.g. https://github.com/stactools-packages/noaa-cdr/pull/36#issue-1401677703. If you agree with this approach, we should remove the `datetime` on items.

**Comment by m-mohr** [comment]
I agree, I just have in mind again that some people complained about not having the datetime because they need a single datetime for their databases and easier searching (i.e. some implementations won't find items that only have start/end_datetime)

**Comment by gadomski** [comment]
> I agree, I just have in mind again that some people complained about not having the datetime because they need a single datetime for their databases and easier searching (i.e. some implementations won't find items that only have start/end_datetime)

I think this is one case where we can be a little specific with how we build -- since the Planetary Computer supports `null` datetimes, and `null` datetimes are valid via the spec, we can build the items that way. If someone needs to add a `datetime` in the future to support a "broken" implementation, it's not hard for them to augment items downstream.

**Comment by m-mohr** [comment]
I wasn't arguing against doing it, that was just meant as a general note...

**Comment by m-mohr** [comment]
A slight annoyance in pystac: https://github.com/stac-utils/pystac/issues/905

**Comment by m-mohr** [comment]
Implemented: 88e4e0ec (quite a lot of changes for a - I thought - very minor change)
