### ISSUE TITLE
Remove GSD

### ISSUE THREAD

**Issue by gadomski** [stactools-packages/esa-cci-lc#7]
We've been using `raster:bands -> spatial_resolution` instead of `gsd` for pixel size. From our reading of the spec, GSD applies to the sensor resolution, while `raster:bands -> spatial_resolution` seems more appropriate for a land cover product.

**Comment by m-mohr** [comment]
Yeah, while I agree I hate that we don't have a way to globally specify the spatial resolution because you can't easily search for the resolution then and also you can't summarize it easily. That's also the reason I mis-used gsd, because I found it has advantages that IMHO outhweigh the "conflict", but ideally we would have spatial_resolution in common metadata...

**Comment by gadomski** [comment]
> you can't easily search for the resolution then and also you can't summarize it easily

In this case, since all the data are the same resolution (I think), then what's the value in searching/summarizing it? 

> ideally we would have spatial_resolution in common metadata

I agree with this.

**Comment by m-mohr** [comment]
> In this case, since all the data are the same resolution (I think), then what's the value in searching/summarizing it?

Searching: If you search across collections it's useful.
Summarizing: Just looking at the collection is then enough to know the spatial resolution, otherwise you need to look into assets directly or open an item. That's not user-friendly.

**Comment by m-mohr** [comment]
Opened https://github.com/radiantearth/stac-spec/issues/1196

**Comment by gadomski** [comment]
> Searching: If you search across collections it's useful.

IMO it's pretty uncommon to say "I only want data at this spatial resolution", especially since many collections have items w/ assets of various spatial resolutions? But maybe that's just my use-bias.

>  Summarizing: Just looking at the collection is then enough to know the spatial resolution, otherwise you need to look into assets directly or open an item. That's not user-friendly.

`item_assets` takes care of this, yes?

**Comment by m-mohr** [comment]
Hmm, we added gsd exactly for that purpose actually so that you can easily search for "I want at least this resolution"...

Sometimes it does, sometimes it doesn't. It's also just more buried... but that's just a general note again. I'll migrate to raster:bands. :-)

**Comment by gadomski** [comment]
> Hmm, we added gsd exactly for that purpose actually so that you can easily search for "I want at least this resolution"...

Ok, that makes sense. I'm not against it per se, it's just very confusing to me how the semantics of GSD are different at the item level than at the asset level. I think we agree :-)

**Comment by m-mohr** [comment]
Why are they different?

**Comment by gadomski** [comment]
I guess they aren't different, but the text in the item spec (https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#additional-fields-for-assets) is much less specific than the common metadata text (https://github.com/radiantearth/stac-spec/blob/master/item-spec/common-metadata.md#gsd), and so I could see people who just read the item spec thinking that GSD is suitable for pixel size in land cover.

**Comment by m-mohr** [comment]
Each COG bands now has the following raster information instead of the GSD.
```
      "raster:bands": [
        {
          "spatial_resolution": 300,
          "sampling": "area",
          "nodata": 0
        }
      ],
```
There are no information about the resolution if only netcdf is exported.
